In [2]:
import pandas as pd
import numpy as np
import xgboost
import warnings
warnings.filterwarnings('ignore')

In [100]:
data = pd.read_csv('data_file.csv')
data

FileName  \
0               0124e21d-018c-4ce0-92a3-b9e205a76bc0.dll   
1           05c8318f98a5d301d80000009c316005.vertdll.dll   
2               06054fba-5619-4a86-a861-ffb0464bef5d.dll   
3            075822ac99a5d301660400009c316005.adhapi.dll   
4      090607dd9ba5d301ca0900009c316005.SensorsNative...   
...                                                  ...   
62480        VirusShare_a43ceb5e5fffc793e0205d15a0606cb0   
62481        VirusShare_0190dafc8304111a00fccf57340ea6a4   
62482        VirusShare_0f3ca55979aaf59158d6b01140696e44   
62483        VirusShare_fca5ce35f1690db6babca5aa5d559535   
62484        VirusShare_d7955a7e6d1e16800feafd4204cbac2b   

                                md5Hash  Machine  DebugSize  DebugRVA  \
0      79755c51e413ed3c6be4635fd729a6e1      332          0         0   
1      95e19f3657d34a432eada93221b0ea16    34404         84    121728   
2      85c32641d77a54e19ba8ea4ab305c791      332          0         0   
3      62e3b959d982ef534b66f819fe15f085    34404         84     19904   
4      ae38c5f7d313ad0ff3bfb8826476767f    34404         84     97728   
...                                 ...      ...        ...       ...   
62480  a43ceb5e5fffc793e0205d15a0606cb0      332          0         0   
62481  0190dafc8304111a00fccf57340ea6a4      332          0         0   
62482  0f3ca55979aaf59158d6b01140696e44      332          0         0   
62483  fca5ce35f1690db6babca5aa5d559535      332          0         0   
62484  d7955a7e6d1e16800feafd4204cbac2b      332          0         0   

       MajorImageVersion  MajorOSVersion  ExportRVA  ExportSize  IatVRA  \
0                      0               4          0           0    8192   
1                     10              10     126576        4930       0   
2                      0               4          0           0    8192   
3                     10              10      21312         252   18160   
4                     10              10     105792        1852   70592   
...                  ...             ...        ...         ...     ...   
62480                  1               4          0           0    4096   
62481                  7              10          0           0       0   
62482                  0               4          0           0  404908   
62483                  0               4      14448          70    4096   
62484                  0               5          0           0    4096   

       MajorLinkerVersion  MinorLinkerVersion  NumberOfSections  \
0                       8                   0                 3   
1                      14                  10                 8   
2                       8                   0                 3   
3                      14                  10                 6   
4                      14                  10                 7   
...                   ...                 ...               ...   
62480                   6                   0                 3   
62481                   7                   0                 7   
62482                   2                  50                11   
62483                   8                   0                 4   
62484                   9                   0                 6   

       SizeOfStackReserve  DllCharacteristics  ResourceSize  BitcoinAddresses  \
0                 1048576               34112           672                 0   
1                  262144               16864          1024                 0   
2                 1048576               34112           672                 0   
3                  262144               16736          1040                 0   
4                  262144               16736          1096                 0   
...                   ...                 ...           ...               ...   
62480             1048576                   0         23504                 0   
62481             1048576                   0         15704                 0   
62482          

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62485 entries, 0 to 62484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   FileName            62485 non-null  object
 1   md5Hash             62485 non-null  object
 2   Machine             62485 non-null  int64 
 3   DebugSize           62485 non-null  int64 
 4   DebugRVA            62485 non-null  int64 
 5   MajorImageVersion   62485 non-null  int64 
 6   MajorOSVersion      62485 non-null  int64 
 7   ExportRVA           62485 non-null  int64 
 8   ExportSize          62485 non-null  int64 
 9   IatVRA              62485 non-null  int64 
 10  MajorLinkerVersion  62485 non-null  int64 
 11  MinorLinkerVersion  62485 non-null  int64 
 12  NumberOfSections    62485 non-null  int64 
 13  SizeOfStackReserve  62485 non-null  int64 
 14  DllCharacteristics  62485 non-null  int64 
 15  ResourceSize        62485 non-null  int64 
 16  BitcoinAddresses    62

In [189]:
data.shape

(62485, 18)

In [190]:
data2.Benign.unique()

array([1, 0], dtype=int64)

In [191]:
data2.Benign.value_counts()

0    35367
1    27118
Name: Benign, dtype: int64

In [11]:
data2.Benign.value_counts(normalize = True)

0    0.566008
1    0.433992
Name: Benign, dtype: float64

In [192]:
# import pickle
# from sklearn import model_selection
# import sklearn.ensemble as ske
# import sklearn.metrics
# from sklearn.metrics import f1_score
# import joblib
# from xgboost import XGBClassifier

# # Main code function that trains the random forest algorithm on dataset.
# def main():
#     print('\n[+] Training MLRD using Random Forest Algorithm...')

#     # Creates pandas dataframe and reads in csv file.
#     data = pd.read_csv('data_file.csv', sep=',')

#     # Drops FileName, md5Hash and Label from data.
#     X = data.drop(['FileName', 'md5Hash', 'Benign'], axis=1).values

#     # Assigns y to label
#     y = data['Benign'].values

#     # Splitting data into training and test data
#     X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=42)

#     # Print the number of training and testing samples.
#     print("\n\t[*] Training samples: ", len(X_train))
#     print("\t[*] Testing samples: ", len(X_test))

#     # Train Random forest algorithm on training dataset.
#     model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
#     model.fit(X_train, y_train)

# #     clf = 
# #     clf.fit(X_train, y_train)

#     # Perform cross validation and print out accuracy.
#     score = model_selection.cross_val_score(model, X_test, y_test, cv=10)
#     print("\n\t[*] Training Score [Accuracy]: ",model.score(X_train, y_train))
#     print("\n\t[*] Test Score [Accuracy]: ",model.score(X_test, y_test))
#     print("\n\t[*] Cross Validation Score: ", round(score.mean()*100, 2), '%')

#     # Calculate f1 score.
#     y_train_pred = model_selection.cross_val_predict(model, X_train, y_train, cv=3)
#     f = f1_score(y_train, y_train_pred)
#     print("\t[*] F1 Score: ", round(f*100, 2), '%')

# if __name__ == '__main__':
#     main()


In [9]:
# XGBOOST MODEL
import pickle
from sklearn import model_selection
import sklearn.ensemble as ske
import sklearn.metrics
from sklearn.metrics import f1_score
import joblib
from xgboost import XGBClassifier

In [271]:


data = pd.read_csv('data_file.csv', sep=',')
# Features
X = data.drop(['FileName', 'md5Hash', 'Benign','Machine'], axis=1).values
# Label
y = data['Benign'].values
 # Splitting data into training and test data
x_train_xgb, x_test_xgb, y_train_xgb, y_test_xgb = model_selection.train_test_split(X, y,test_size = 0.2,random_state=42)

xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(x_train_xgb, y_train_xgb)

score = model_selection.cross_val_score(xgb_model, x_test, y_test, cv=10)
# print("\n\t[*] Training Score [Accuracy]: ",xgb_model.score(x_train, y_train))
# print("\n\t[*] Test Score [Accuracy]: ",xgb_model.score(x_test, y_test))
# print("\n\t[*] Cross Validation Score: ", round(score.mean()*100, 2), '%')


In [ ]:
# xgb_model.fit(x_train, y_train)

In [272]:
xgb_model.score(x_train, y_train)

0.9988197167320156

In [273]:
xgb_model.predict(x_test)

array([0, 1, 1, ..., 1, 0, 1])

In [250]:
x_train.shape, x_test.shape

((49988, 14), (12497, 14))

In [257]:
b = x_test[0]
# b
pred4 = xgb_model.predict([b])

In [ ]:
#LSTM

In [291]:
from keras.models import Sequential
from keras.layers import *
from keras.callbacks import ModelCheckpoint
from keras.losses import MeanSquaredError
from keras.metrics import RootMeanSquaredError
from keras.optimizers import Adam
from keras.layers import Dropout
from keras.models import load_model
    
    


In [274]:
from sklearn.model_selection import train_test_split
x_train_lstm,x_test_lstm,y_train_lstm,y_test_lstm= train_test_split(X, y, test_size = 0.20)

In [275]:
# Features
X = data.drop(['FileName', 'md5Hash', 'Benign','Machine'], axis=1).values
# Label
y = data['Benign'].values
 # Splitting data into training and test data
x_train_lstm,x_test_lstm,y_train_lstm,y_test_lstm= train_test_split(X, y, test_size = 0.20)


In [234]:
# from sklearn.preprocessing import MinMaxScaler
# mms = MinMaxScaler()
# mms.fit(x_train)
# x_train = mms.transform(x_train)
# x_test = mms.transform(x_test)

In [176]:
# model = Sequential()
# model.add(Dense(100, input_dim = 13, activation='relu')
# model.add(Dense(100, activation='relu')
# model.add(Dense(1, activation='linear'))

In [276]:
data.shape

(62485, 18)

In [277]:
x_train.shape

(49988, 14)

In [278]:
# reshape the input data for an LSTM network
x_train_lstm = x_train_lstm.reshape(x_train_lstm.shape[0], 1, x_train_lstm.shape[1])
x_test_lstm = x_test_lstm.reshape(x_test_lstm.shape[0], 1, x_test_lstm.shape[1])

In [280]:
x_train_lstm.shape

(49988, 1, 14)

In [288]:
# define the model
model2 = Sequential()
model2.add(LSTM(50, input_shape=(1, 14), return_sequences = True))
model2.add(Dropout(0.2))
model2.add(LSTM(50,return_sequences = False))
model2.add(Dense(1, activation='softmax'))
# model.compile(loss='binary-crossentropy', optimizer='adam')

# # fit the model to the training data
# model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))


model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.fit(x_train_lstm, y_train_lstm, epochs=5, batch_size=32, validation_data=(x_test_lstm,
                                                                                 y_test_lstm))

# model.compile(loss='categorical_crossentropy',
#               optimizer='adam',
#               metrics=['accuracy'])


Epoch 1/5
1563/1563 [==============================] - 15s 9ms/step - loss: 8.6305 - accuracy: 0.4340 - val_loss: 8.6344 - val_accuracy: 0.4338
Epoch 2/5
1563/1563 [==============================] - 14s 9ms/step - loss: 8.6305 - accuracy: 0.4340 - val_loss: 8.6344 - val_accuracy: 0.4338
Epoch 3/5
1563/1563 [==============================] - 17s 11ms/step - loss: 8.6305 - accuracy: 0.4340 - val_loss: 8.6344 - val_accuracy: 0.4338
Epoch 4/5
1563/1563 [==============================] - 17s 11ms/step - loss: 8.6305 - accuracy: 0.4340 - val_loss: 8.6344 - val_accuracy: 0.4338
Epoch 5/5
1563/1563 [==============================] - 17s 11ms/step - loss: 8.6305 - accuracy: 0.4340 - val_loss: 8.6344 - val_accuracy: 0.4338


In [290]:
model2.evaluate(x_train_lstm, y_train_lstm)
# j

1563/1563 [==============================] - 6s 4ms/step - loss: 8.6305 - accuracy: 0.4340


[8.630472183227539, 0.4340441823005676]

In [292]:
model2.save('my_lstm_model.h5')  # creates a HDF5 file 'my_model.h5'
#     del model  # deletes the existing model
    
#     # returns a compiled model
#     # identical to the previous one
#     model = load_model('my_model.h5')


In [121]:
# b = [[56,  147600,       0,       4,  148496,     186,
#          147456,       5,      12,       5, 1048576,       0,     808,
#               0]]
# model.predict(b)
# b  = [  332,      56,  147600,       0,       4,  148496,     186,
#         147456,       5,      12,       5, 1048576,       0,     808,
#               0]
# # b = np.array(b)
# # model.predict(b)

# b = b.reshape(b.shape[0], 1, b.shape[1])

In [245]:
b = x_test[0]
c = b.reshape(b.shape[0], 1, b.shape[1])
pred5 = model2.predict(c)


# ## Stop here

array([      0,       0,       0,       4,       0,       0,   40960,
             9,       0,       5, 1048576,       0,   43928,       0],
      dtype=int64)

In [334]:
import numpy as np
from sklearn.datasets import load_boston
from hmmlearn import hmm

In [357]:
data = pd.read_csv('data_file.csv', sep=',')


In [358]:
#Dropping some collumns including the target featvariableure
X = data.drop(['FileName','md5Hash','Machine', 'Benign'], axis=1)
#Isolating the target variable (1 is Malicious 0 is Benign)
y = data['Benign']

In [359]:
#Train Test Splitting and putting the data into numpy arrays. And creating collumn stacks.
x_train_hmm, x_test_hmm, y_train_hmm, y_test_hmm = train_test_split(X, y, test_size=0.2)
npX_train_hmm=np.array(X)
npy_train_hmm=np.array(y)
train_features=np.column_stack((npX_train_hmm,npy_train_hmm))

npX_test_hmm=np.array(x_test_hmm)
npy_test_hmm=np.array(y_test_hmm)
test_features=np.column_stack((npX_test_hmm,npy_test_hmm))


In [360]:
x_train_hmm.shape, x_test_hmm.shape

((49988, 14), (12497, 14))

In [361]:
#Creating the HMM model and fitting the data
from hmmlearn.hmm import GaussianHMM
hmm = GaussianHMM(n_components = 2, covariance_type = "diag", n_iter = 50, random_state = 42)
hmm.fit(train_features)

GaussianHMM(n_components=2, n_iter=50, random_state=42)

In [362]:
#Predicting HMM
Z = hmm.predict(test_features)

In [339]:
Z.shape

(12497,)

In [369]:
b = x_test_hmm[:1]
test_b = np.array(b)
test_b = np.column_stack(test_b)
pred6 = hmm.predict(test_b)
pred6


# Example stops here

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [381]:
pred4.shape

(1,)

In [380]:

pred5.shape

(1, 1)

In [383]:
pred6.shape

(14,)

In [384]:
b = x_test_hmm[:1]
b

DebugSize  DebugRVA  MajorImageVersion  MajorOSVersion  ExportRVA  \
55572         28    155648                  0               4     166128   

       ExportSize  IatVRA  MajorLinkerVersion  MinorLinkerVersion  \
55572         392   78352                   8                   0   

       NumberOfSections  SizeOfStackReserve  DllCharacteristics  ResourceSize  \
55572                 7             1048576                  64          2808   

       BitcoinAddresses  
55572                 0

In [385]:
test_b = np.array(b)
test_b = np.column_stack(test_b)
pred6 = hmm.predict(test_b)
pred6


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [373]:
train_features

array([[     0,      0,      0, ...,    672,      0,      1],
       [    84, 121728,     10, ...,   1024,      0,      1],
       [     0,      0,      0, ...,    672,      0,      1],
       ...,
       [     0,      0,      0, ...,   2364,      0,      0],
       [     0,      0,      0, ..., 130296,      0,      0],
       [     0,      0,      0, ...,   6912,      0,      0]], dtype=int64)

In [144]:
test_features

array([[     0,      0,      0, ...,    672,      0,      1],
       [    84, 121728,     10, ...,   1024,      0,      1],
       [     0,      0,      0, ...,    672,      0,      1],
       ...,
       [     0,      0,      0, ...,   2364,      0,      0],
       [     0,      0,      0, ..., 130296,      0,      0],
       [     0,      0,      0, ...,   6912,      0,      0]], dtype=int64)

In [145]:
X

DebugSize  DebugRVA  MajorImageVersion  MajorOSVersion  ExportRVA  \
0              0         0                  0               4          0   
1             84    121728                 10              10     126576   
2              0         0                  0               4          0   
3             84     19904                 10              10      21312   
4             84     97728                 10              10     105792   
...          ...       ...                ...             ...        ...   
62480          0         0                  1               4          0   
62481          0         0                  7              10          0   
62482          0         0                  0               4          0   
62483          0         0                  0               4      14448   
62484          0         0                  0               5          0   

       ExportSize  IatVRA  MajorLinkerVersion  MinorLinkerVersion  \
0               0    8192                   8                   0   
1            4930       0                  14                  10   
2               0    8192                   8                   0   
3             252   18160                  14                  10   
4            1852   70592                  14                  10   
...           ...     ...                 ...                 ...   
62480           0    4096                   6                   0   
62481           0       0                   7                   0   
62482           0  404908                   2                  50   
62483          70    4096                   8                   0   
62484           0    4096                   9                   0   

       NumberOfSections  SizeOfStackReserve  DllCharacteristics  ResourceSize  \
0                     3             1048576               34112           672   
1                     8              262144               16864          1024   
2                     3             1048576               34112           672   
3                     6              262144               16736          1040   
4                     7              262144               16736          1096   
...                 ...                 ...                 ...           ...   
62480                 3             1048576                   0         23504   
62481                 7             1048576                   0         15704   
62482                11             1048576                   0          2364   
62483                 4             1048576                   0        130296   
62484                 6             1048576                   0          6912   

       BitcoinAddresses  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
62480                 0  
62481                 0  
62482                 0  
62483                 0  
62484                 0  

[62485 rows x 14 columns]

In [146]:
Z

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [147]:
X.shape

(62485, 14)

In [ ]:
# Define a function to ensemble the predictions
def ensemble_predictions(pred1, pred2, pred3):
  return (pred1 + pred2 + pred3) / 3

# Make predictions using each model
pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)

# Ensemble the predictions
predictions = ensemble_predictions(pred1, pred2, pred3)

In [374]:
# Define a function to ensemble the predictions
def ensemble_predictions(pred1, pred2, pred3):
  return (pred1 + pred2 + pred3) / 3

In [344]:
# Make predictions using each model
pred1 = xgb_model.predict(x_test_xgb)

# pred3 = model3.predict(X_test)


In [345]:
pred2 = model2.predict(x_test_lstm)

In [346]:
pred3 = hmm.predict(test_features)

In [347]:
# Ensemble the predictions
predictions = ensemble_predictions(pred1, pred2, pred3)

In [348]:
predictions

array([[0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       ...,
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667]])

In [349]:
ensemble_predictions(pred1, pred2, pred3)

array([[0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       ...,
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667],
       [0.33333333, 0.66666667, 0.66666667, ..., 0.66666667, 0.33333333,
        0.66666667]])

In [375]:
# xgboost model prediction
pred4

array([0])

In [376]:
# LSTM prediction
pred5

array([[1.]], dtype=float32)

In [377]:
# HMM prediction
pred6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [378]:
ensemble_predictions(pred4, pred5, pred6)

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [ ]:
# Z = hmm.predict(test_features)

In [123]:
d = [[0, 808,
              0]]
e = np.array(d)
e = np.column_stack(e)
hmm.predict(e)

array([0, 0, 0], dtype=int64)

In [97]:
model = HMM(transition_probs, emission_probs)
model.fit(data)

NameError: name 'HMM' is not defined

In [388]:
# xgboost model prediction
pred4

array([0])

In [389]:
# LSTM prediction
pred5

array([[1.]], dtype=float32)

In [390]:
# ensemble xgboost and LSTM
def ensemble_prediction(pred1, pred2):
  return (pred1 + pred2) / 2

In [391]:
ensemble_prediction(pred4, pred5)

array([[0.5]])

In [194]:
# cols = list(df)[0:15]
# cols

In [68]:
# df = df[cols].astype(str)
# for i in cols:
#     for j in range(0, len(df)):
#         df[i][j] = df[i][j].replace(',', '')

# df = df.astype(float)

# # Using multiple features (predictors)
# df = df.to_numpy() 

# print('Shape of data set == {}.'.format(df.shape))
# df


In [195]:
# X = data.drop(['FileName', 'md5Hash', 'Benign'], axis=1).values
# # Label
# y = data['Benign'].values
#  # Splitting data into training and test data
# X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=0)


In [25]:
b = [[  332,      56,  147600,       0,       4,  148496,     186,
         147456,       5,      12,       5, 1048576,       0,     808,
              0]]
b = np.array(b)
hmm_model.predict(b)

ValueError: operands could not be broadcast together with shapes (1,1,15) (5,16) 

In [36]:
X[0]

array([    332,       0,       0,       0,       4,       0,       0,
          8192,       8,       0,       3, 1048576,   34112,     672,
             0], dtype=int64)

In [5]:
# import joblib

In [6]:
# filename = 'xgboost_model.pkl'
# joblib.dump(model, filename)

['xgboost_model.pkl']

In [10]:
test = [[332,0,0,0,4,0,0,8192,8,0,3,1048576,34112,672,0]]

In [42]:
model.predict(X_test[:2])

array([0, 1])

In [49]:
X_train[2]

array([    332,      28,   88660,       0,       4,       0,       0,
          8192,      11,       0,       3, 1048576,   34112,    1432,
             0], dtype=int64)

In [64]:
import numpy as np
np.array([-9.035250067710876], [7.453250169754028], [33.34074878692627])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [12]:
import numpy as np

In [20]:
a = [[332,28,4768,6,6,96144,166,4096,9,0,4,262144,448,4048,0]]
a = np.array(a)

In [21]:
X_train[1]

array([    332,      28,  291712,       0,       4,       0,       0,
          8192,      48,       0,       3, 1048576,   34112,    1220,
             0], dtype=int64)

In [22]:
model.predict(a) 

array([1])

In [80]:
X_train[:2]

array([[    332,      56,  147600,       0,       4,  148496,     186,
         147456,       5,      12,       5, 1048576,       0,     808,
              0],
       [    332,      28,  291712,       0,       4,       0,       0,
           8192,      48,       0,       3, 1048576,   34112,    1220,
              0]], dtype=int64)

In [81]:
b = [[  332,      56,  147600,       0,       4,  148496,     186,
         147456,       5,      12,       5, 1048576,       0,     808,
              0]]
b = np.array(b)
model.predict(b)

array([0])

In [83]:
model.predict(X_train)

array([0, 1, 1, ..., 1, 1, 0])

In [80]:
'''
    File name: create_benign_dataset.py
    Author: Callum Lock
    Date created: 31/03/2018
    Date last modified: 31/03/2018
    Python Version: 3.6
'''

import os
import hashlib
import math
import array
import pefile
import yara
from termcolor import colored
import colorama


# Function get md5 calculates the md5 hash of a given file.
def get_md5(file):
    
    # Note that sometimes you won't be able to fit the whole file in memory.
    # In that case, you'll have to read chunks of 4096 bytes
    # sequentially and feed them to the Md5 function:
    # https://stackoverflow.com/questions/3431825/generating-an-md5-checksum-of-a-file
    
    md5 = hashlib.md5()
    with open(file, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            md5.update(chunk)
        return md5.hexdigest()

# Function compile bitcoin compiles the yara rule for detecting
# bitcoin addresses within ransomware files. The rule is then
# saved in a directory to later be used.
def compile_bitcoin():
    if not os.path.isdir("rules_compiled/Bitcoin"):
        os.makedirs("rules_compiled/Bitcoin")
        print("success")

    for n in os.listdir("rules/Bitcoin"):
        rule = yara.compile("rules/Bitcoin/" + n)
        rule.save("rules_compiled/Bitcoin/" + n)

# Function check bitcoin loads the bitcoin yara rule
# and checks a file for any signs of bitcoin addresses.
# If a bitcoin address is found a binary 1 is returned.
def check_bitcoin(filepath):
    for n in os.listdir("rules/Bitcoin"):
        rule = yara.load("rules_compiled/Bitcoin/" + n)
        m = rule.match(filepath)
        if m:
            return 1
        else:
            return 0

# Function extract features extracts all features from the input file.
# Features are stored in a list and then returned to later be written to
# a csv file. 
def extract_features(file):
    # Creates an empty list for which features can later be appended into.
    features = []

    # Name of file
    features.append(os.path.basename(file))

    # MD5 hash
    features.append(get_md5(file))

    # Assigns pe to the input file. fast_load loads all directory information.
    pe = pefile.PE(file, fast_load=True)

    # CPU that the file is intended for.
    features.append(pe.FILE_HEADER.Machine)

    # DebugSize is the size of the debug directory table. Clean files typically have a debug directory
    # and thus, will have a non-zero values.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[6].Size)

    # DebugRVA
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[6].VirtualAddress)

    # MajorImageVersion is the version of the file. This is user defined and for clean programs is often
    # populated. Malware often has a value of 0 for this.
    features.append(pe.OPTIONAL_HEADER.MajorImageVersion)

    # MajorOSVersion is the major operating system required to run exe.
    features.append(pe.OPTIONAL_HEADER.MajorOperatingSystemVersion)

    # ExportRVA.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[0].VirtualAddress)

    # ExportSize is the size of the export table. Usually non-zero for clean files.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[0].Size)

    # IatRVA is the relative virtual address of import address table. Most clean files have 4096 for this
    # where as malware often has 0 or a very large number.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[12].VirtualAddress)

    # Version of linker that produced file.
    features.append(pe.OPTIONAL_HEADER.MajorLinkerVersion)
    features.append(pe.OPTIONAL_HEADER.MinorLinkerVersion)

    # NumberOfSections is the number of sections in file.
    features.append(pe.FILE_HEADER.NumberOfSections)

    # SizeOfStackReserve denotes the amount of virtual memory to reserve for the initial thread's stack.
    features.append(pe.OPTIONAL_HEADER.SizeOfStackReserve)

    # DllCharacteristics is a set of flags indicating under which circumstances a DLL's initialization
    # function will be called.
    features.append(pe.OPTIONAL_HEADER.DllCharacteristics)

    # MinResourcesSize is the size of resources section of PE header. Malware sometimes has 0 resources.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[2].Size)

    # Calls the bitcoin_check function to check if the file contains a bitcoin address.
    bitcoin_check = check_bitcoin(file)
    features.append(bitcoin_check)

    # Returns the feature list.
    return features


if __name__ == '__main__':
    output_file = "data2_benign.csv"
    csv_delimeter = ','
    csv_columns = [
        "FileName",
        "md5Hash",
        "Machine",
        "DebugSize",
        "DebugRVA",
        "MajorImageVersion",
        "MajorOSVersion",
        "ExportRVA",
        "ExportSize",
        "IatVRA",
        "MajorLinkerVersion",
        "MinorLinkerVersion",
        "NumberOfSections",
        "SizeOfStackReserve",
        "DllCharacteristics",
        "ResourceSize",
        "BitcoinAddresses",
        "Benign",
    ]

    # Compiles the yara rule for bitcoin address detection.
    compile_bitcoin()

    # Opens file so features can be written too.
    feature_file = open(output_file, 'a')
    
    # Writes column headers to feature file.
    feature_file.write(csv_delimeter.join(csv_columns) + "\n")

    colorama.init()

    # Extracts features from benign files and writes to CSV.
    for f in os.listdir('benign/'):
        print("\n[+] Extracting features from ", f)
        try:
            features = extract_features(os.path.join('benign/', f))
            features.append(1)
            feature_file.write(csv_delimeter.join(map(lambda x: str(x), features)) + "\n")
            print(colored("[*] Features extracted successfully.\n", 'green'))
        except:
            print(colored("[-] Error: Unable to extract features.\n", 'red'))

    feature_file.close()



[+] Extracting features from  test.txt
[-] Error: Unable to extract features.



In [89]:


if __name__ == '__main__':
    output_file = "data2_benign.csv"
    csv_delimeter = ','
    csv_columns = [
        "FileName",
        "md5Hash",
        "Machine",
        "DebugSize",
        "DebugRVA",
        "MajorImageVersion",
        "MajorOSVersion",
        "ExportRVA",
        "ExportSize",
        "IatVRA",
        "MajorLinkerVersion",
        "MinorLinkerVersion",
        "NumberOfSections",
        "SizeOfStackReserve",
        "DllCharacteristics",
        "ResourceSize",
        "BitcoinAddresses",
        "Benign",
    ]

    # Compiles the yara rule for bitcoin address detection.
    compile_bitcoin()

    # Opens file so features can be written too.
    feature_file = open(output_file, 'a')
    
    # Writes column headers to feature file.
    feature_file.write(csv_delimeter.join(csv_columns) + "\n")

    colorama.init()

    # Extracts features from benign files and writes to CSV.
    for f in os.listdir(r'C:\Users\Mustapha\Desktop\New_folder_(2)\Django_project\env\Scripts'):
        print("\n[+] Extracting features from ", f)
        try:
            features = extract_features(os.path.join('benign/', f))
            features.append(1)
            feature_file.write(csv_delimeter.join(map(lambda x: str(x), features)) + "\n")
            print(colored("[*] Features extracted successfully.\n", 'green'))
        except:
            print(colored("[-] Error: Unable to extract features.\n", 'red'))

    feature_file.close()


[+] Extracting features from  activate
[-] Error: Unable to extract features.


[+] Extracting features from  activate.bat
[-] Error: Unable to extract features.


[+] Extracting features from  activate.fish
[-] Error: Unable to extract features.


[+] Extracting features from  activate.nu
[-] Error: Unable to extract features.


[+] Extracting features from  activate.ps1
[-] Error: Unable to extract features.


[+] Extracting features from  activate_this.py
[-] Error: Unable to extract features.


[+] Extracting features from  deactivate.bat
[-] Error: Unable to extract features.


[+] Extracting features from  deactivate.nu
[-] Error: Unable to extract features.


[+] Extracting features from  django-admin.exe
[-] Error: Unable to extract features.


[+] Extracting features from  normalizer.exe
[-] Error: Unable to extract features.


[+] Extracting features from  pip-3.9.exe
[-] Error: Unable to extract features.


[+] Extracting features from  pip.exe
[-] Error: Unable to extract 

In [96]:
def extract_features(file):
    # Creates an empty list for which features can later be appended into.
    features = []

    # Name of file
#     features.append(os.path.basename(file))

    # MD5 hash
    features.append(get_md5(file))

    # Assigns pe to the input file. fast_load loads all directory information.
    pe = pefile.PE(file, fast_load=True)

    # CPU that the file is intended for.
    features.append(pe.FILE_HEADER.Machine)

    # DebugSize is the size of the debug directory table. Clean files typically have a debug directory
    # and thus, will have a non-zero values.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[6].Size)

    # DebugRVA
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[6].VirtualAddress)

    # MajorImageVersion is the version of the file. This is user defined and for clean programs is often
    # populated. Malware often has a value of 0 for this.
    features.append(pe.OPTIONAL_HEADER.MajorImageVersion)

    # MajorOSVersion is the major operating system required to run exe.
    features.append(pe.OPTIONAL_HEADER.MajorOperatingSystemVersion)

    # ExportRVA.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[0].VirtualAddress)

    # ExportSize is the size of the export table. Usually non-zero for clean files.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[0].Size)

    # IatRVA is the relative virtual address of import address table. Most clean files have 4096 for this
    # where as malware often has 0 or a very large number.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[12].VirtualAddress)

    # Version of linker that produced file.
    features.append(pe.OPTIONAL_HEADER.MajorLinkerVersion)
    features.append(pe.OPTIONAL_HEADER.MinorLinkerVersion)

    # NumberOfSections is the number of sections in file.
    features.append(pe.FILE_HEADER.NumberOfSections)

    # SizeOfStackReserve denotes the amount of virtual memory to reserve for the initial thread's stack.
    features.append(pe.OPTIONAL_HEADER.SizeOfStackReserve)

    # DllCharacteristics is a set of flags indicating under which circumstances a DLL's initialization
    # function will be called.
    features.append(pe.OPTIONAL_HEADER.DllCharacteristics)

    # MinResourcesSize is the size of resources section of PE header. Malware sometimes has 0 resources.
    features.append(pe.OPTIONAL_HEADER.DATA_DIRECTORY[2].Size)

    # Calls the bitcoin_check function to check if the file contains a bitcoin address.
    bitcoin_check = check_bitcoin(file)
    features.append(bitcoin_check)

    # Returns the feature list.
    return features

In [53]:
# extract_features('benign')

In [74]:
file = os.path.basename('benign/test.txt')

In [61]:
get_md5('benign/test.txt')

'25289c2b803207cce00cf4b282949750'

In [78]:
pe = pefile.PE(r'C:\Users\Mustapha\Desktop\New_folder_(2)\Django_project\env\Scripts\normalizer.exe', fast_load=True)

In [22]:
def get_md5(file):
    
    # Note that sometimes you won't be able to fit the whole file in memory.
    # In that case, you'll have to read chunks of 4096 bytes
    # sequentially and feed them to the Md5 function:
    # https://stackoverflow.com/questions/3431825/generating-an-md5-checksum-of-a-file
    
    md5 = hashlib.md5()
    with open(file, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            md5.update(chunk)
        return md5.hexdigest()

In [30]:
get_md5('benign/test.txt')

'25289c2b803207cce00cf4b282949750'

In [97]:
 extract_features(r'C:\Users\Mustapha\Desktop\New_folder_(2)\Django_project\security\MLRD-Machine-Learning-Ransomware-Detection\benign\normalizer.exe')

['46de421fa3f48785fdcf7572d08f61f7',
 34404,
 28,
 66368,
 0,
 5,
 0,
 0,
 65536,
 10,
 0,
 6,
 1048576,
 33088,
 21492,
 0]

In [25]:
import hashlib
def md5(fname):
    hash_md5 = hashlib.md5()
    with open(fname, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()

In [28]:
 md5('benign/test.txt')

'25289c2b803207cce00cf4b282949750'

In [11]:
import pandas as pd

In [13]:
# Malicious files
# Malicious files
# Malicious files
# Malicious files
df = pd.read_csv('data_benign.csv')
df.head()

<ipython-input-13-19450828a73f>:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data_benign.csv')


FileName  \
0           0124e21d-018c-4ce0-92a3-b9e205a76bc0.dll   
1       05c8318f98a5d301d80000009c316005.vertdll.dll   
2           06054fba-5619-4a86-a861-ffb0464bef5d.dll   
3        075822ac99a5d301660400009c316005.adhapi.dll   
4  090607dd9ba5d301ca0900009c316005.SensorsNative...   

                            md5Hash Machine DebugSize DebugRVA  \
0  79755c51e413ed3c6be4635fd729a6e1     332         0        0   
1  95e19f3657d34a432eada93221b0ea16   34404        84   121728   
2  85c32641d77a54e19ba8ea4ab305c791     332         0        0   
3  62e3b959d982ef534b66f819fe15f085   34404        84    19904   
4  ae38c5f7d313ad0ff3bfb8826476767f   34404        84    97728   

  MajorImageVersion MajorOSVersion ExportRVA ExportSize IatVRA  \
0                 0              4         0          0   8192   
1                10             10    126576       4930      0   
2                 0              4         0          0   8192   
3                10             10     21312        252  18160   
4                10             10    105792       1852  70592   

  MajorLinkerVersion MinorLinkerVersion NumberOfSections SizeOfStackReserve  \
0                  8                  0                3            1048576   
1                 14                 10                8             262144   
2                  8                  0                3            1048576   
3                 14                 10                6             262144   
4                 14                 10                7             262144   

  DllCharacteristics ResourceSize BitcoinAddresses Benign  
0              34112          672                0      1  
1              16864         1024                0      1  
2              34112          672                0      1  
3              16736         1040                0      1  
4              16736         1096                0      1

In [14]:
# Unmalicious files
# Unmalicious files
# Unmalicious files
# Unmalicious files
df2 = pd.read_csv('data_ransomware.csv')
df2

FileName  \
0      VirusShare_0a09a21c2f28c8c5b5d168feb668a80b   
1      VirusShare_bc4ce1d0466f42493418d65b9a1e880f   
2      VirusShare_3086d1682a10bca61945ccca93cc8098   
3      VirusShare_0683b586f3b9ea7a06d4d31555f31f80   
4      VirusShare_d74daee515bd5a77f299151a568cb57a   
...                                            ...   
35362  VirusShare_a43ceb5e5fffc793e0205d15a0606cb0   
35363  VirusShare_0190dafc8304111a00fccf57340ea6a4   
35364  VirusShare_0f3ca55979aaf59158d6b01140696e44   
35365  VirusShare_fca5ce35f1690db6babca5aa5d559535   
35366  VirusShare_d7955a7e6d1e16800feafd4204cbac2b   

                                md5Hash  Machine  DebugSize  DebugRVA  \
0      0a09a21c2f28c8c5b5d168feb668a80b      332          0         0   
1      bc4ce1d0466f42493418d65b9a1e880f      332          0         0   
2      3086d1682a10bca61945ccca93cc8098      332          0         0   
3      0683b586f3b9ea7a06d4d31555f31f80      332          0         0   
4      d74daee515bd5a77f299151a568cb57a      332         28     12336   
...                                 ...      ...        ...       ...   
35362  a43ceb5e5fffc793e0205d15a0606cb0      332          0         0   
35363  0190dafc8304111a00fccf57340ea6a4      332          0         0   
35364  0f3ca55979aaf59158d6b01140696e44      332          0         0   
35365  fca5ce35f1690db6babca5aa5d559535      332          0         0   
35366  d7955a7e6d1e16800feafd4204cbac2b      332          0         0   

       MajorImageVersion  MajorOSVersion  ExportRVA  ExportSize  IatVRA  \
0                      0               4          0           0    8520   
1                      8              10     369716         160       0   
2                      0               4          0           0     257   
3                      0               5          0           0  245760   
4                      0               4          0           0   28672   
...                  ...             ...        ...         ...     ...   
35362                  1               4          0           0    4096   
35363                  7              10          0           0       0   
35364                  0               4          0           0  404908   
35365                  0               4      14448          70    4096   
35366                  0               5          0           0    4096   

       MajorLinkerVersion  MinorLinkerVersion  NumberOfSections  \
0                       6                   0                 2   
1                       9                   0                 3   
2                       2                  50                 5   
3                       9                   0                 7   
4                       9                   0                 8   
...                   ...                 ...               ...   
35362                   6                   0                 3   
35363                   7                   0                 7   
35364                   2                  50                11   
35365                   8                   0                 4   
35366                   9                   0                 6   

       SizeOfStackReserve  DllCharacteristics  ResourceSize  BitcoinAddresses  \
0                 1048576                   0             0                 0   
1                       0                   0           764                 0   
2                 1048576                   0        227484                 0   
3                 1048576               32768         45920                 0   
4                 1048576                   0         96304                 0   
...                   ...                 ...           ...               ...   
35362             1048576                   0         23504                 0   
35363             1048576                   0         15704                 0   
35364             1048576                   0          2364                 0   
